
services:
  backend:
    build: ./backend
    container_name: uniattend-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"
    networks:
      - uniattend-network

  frontend:
    build: ./frontend
    container_name: uniattend-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - uniattend-network

networks:
  uniattend-network:
    driver: bridge
