
services:
  backend:
    build: ./backend
    container_name: uniattend-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"
    networks:
      - uniattend-network

  frontend:
    build: ./frontend
    container_name: uniattend-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://uniattend-app.onrender.com}
    networks:
      - uniattend-network

networks:
  uniattend-network:
    driver: bridge